name: Marathon
description: |
  A container orchestration platform for Mesos and DCOS
version: v1
category: MesosFrameworks
maintainer: James Oliver <joliver@rancher.com>
minimum_rancher_version: v1.0.0
