name: Marathon
description: |
  Orchestrate Mesos frameworks and long-running services
version: v1
category: Orchestration
maintainer: James Oliver <joliver@rancher.com>
minimum_rancher_version: v1.0.0
