zookeeper:
  scale: 3
  retain_ip: true
  health_check:
    port: 2181
    request_line: ''
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
master:
  scale: 3
  retain_ip: true
  health_check:
    port: 5050
    request_line: '/metrics/snapshot'
    interval: 3000
    response_timeout: 2000
    unhealthy_threshold: 2
    healthy_threshold: 2
slave:
  health_check:
    port: 5051
    request_line: ''
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
