.catalog:
  version: v0.15.4
  questions:
  - variable: MARATHON_HTTP_PORT
    description: Port to expose Marathon on.
    label: Marathon Port
    required: true
    type: int
    default: 8080
marathon:
  scale: 1
  health_check:
    port: ${MARATHON_HTTP_PORT}
    interval: 5000
    unhealthy_threshold: 2
    healthy_threshold: 3
    request_line: '/'
    response_timeout: 3000
