k8s-scheduler:
  image: llparse/mesos-k8s:v1.2.4
  command: |
    k8sm-scheduler
      --etcd-servers http://etcd:2379
  links:
  - etcd

k8s:
  image: llparse/kubernetes:latest
  environment:
    GLOG_v: 3
    K8SM_MESOS_MASTER: ${MESOS_MASTER}
    DEFAULT_DNS_NAME: ${DEFAULT_DNS_NAME}
    HOST: ${DOCKER_HOST_IP}
    MESOS_SANDBOX: /data
    DNS_SERVER_IP: 169.254.169.250
    DNS_DOMAIN: rancher.internal
    DNS_NAMESERVERS: 8.8.8.8:53,8.8.4.4:53
    DEBUG: true

etcd:
  image: rancher/etcd:v2.3.6
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: data
    io.rancher.service.allocate.skip.serialize: 'true'
    io.rancher.container.start_once: 'true'
  environment:
    ETCD_DATA_DIR: /data
    ETCDCTL_ENDPOINT: http://etcd:2379
  links:
  - data
  - discovery
  volumes_from:
    - data

data:
  image: busybox
  command: /bin/true
  net: none
  volumes:
  - /data
  labels:
    io.rancher.container.start_once: 'true'

discovery:
  image: rancher/etcd:v2.3.6
  command: discovery_node
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.sidekicks: bootstrap

bootstrap:
  image: rancher/etcd:v2.3.6
  command: bootstrap
  links:
  - discovery
  labels:
    io.rancher.container.start_once: 'true'
  environment:
    ETCDCTL_ENDPOINT: http://etcd:2379