.catalog:
  name: Kubernetes
  version: v1
  questions:
  - variable: MESOS_MASTER
    label: Mesos master addy
    type: string
    default: 127.0.0.1:5050
  - variable: DOCKER_HOST_IP
    label: Docker host ip
    type: string
    default: 127.0.0.1
  - variable: DEFAULT_DNS_NAME
    label: Default DNS name
    type: string
    default: kubernetes.rancher.internal
etcd:
  scale: 3
  health_check:
    port: 2379
    interval: 7500
    unhealthy_threshold: 2
    request_line: '/health'
    healthy_threshold: 2
    response_timeout: 5000
